/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package om.lang.pie

import kotlin.test.Test
import kotlin.test.assertEquals

class InferShould {
    @Test
    fun inferSimpleTypes() {
        assertInferredTo("0", Nat)
        assertInferredTo("1", Nat)
        assertInferredTo("Nat", Set)
        assertInferredTo("Set", Set)
    }

    private fun assertInferredTo(source: String, expected: Type) {
        val sexpr = SExprParser.parseOne(source)
        val expr = SExprToProgram.expr(sexpr)
        assertEquals(expected, infer(expr))
    }
}
