/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package yux.ktcpg

import org.jetbrains.kotlin.psi.KtNamedFunction

object Sources {
    val hello = """
        fun foo(b: Int) {
            val a = 5
            a = 8
        }
    """.trimIndent()
}

object SourceLookers {
    fun hello() {
        val f = parseToKtFile(Sources.hello)
        val fst = f.declarations.first() as KtNamedFunction
        println("valP: " + fst.valueParameters.map { it.text })
        println("children: " + fst.children.map { it.text })
        println("body: " + fst.bodyExpression?.text)
        println("bodyBlock: " + fst.bodyBlockExpression?.text)
    }
}

fun main() {
    SourceLookers.hello()
}
