local queue = require 'queue'

local q = queue.create()
assert(q:isEmpty())
assert(q:peek() == nil)
assert(q:pop() == nil)
assert(q:storageUsage() == 0)

q:appendLeft(1)
assert(not q:isEmpty())
assert(q:peek() == 1)
assert(q:pop() == 1)
assert(q:isEmpty())
assert(q:storageUsage() == 0)

q:appendLeft(2)
q:appendLeft(3)
q:appendLeft(4)
assert(q:storageUsage() == 3)
assert(not q:isEmpty())
assert(q:peek() == 2)
assert(q:pop() == 2)
assert(q:pop() == 3)
assert(q:pop() == 4)
assert(q:isEmpty())
assert(q:storageUsage() == 0)

q:appendLeft(5)
q:appendLeft(6)
q:appendLeft(7)
local xs = q:popWhile(function(x) return true end)
assert(xs[1] == 5)
assert(xs[2] == 6)
assert(xs[3] == 7)
assert(#xs == 3)
assert(q:storageUsage() == 0)

q:appendLeft(8)
q:appendLeft(9)
q:appendLeft(10)
assert(q:foldr(function(x, acc) return x + acc end, 0) == 27)
